Lab3/Lab3/Models/PartidoFecha.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Lab3.Models
{
    public class PartidoFecha : IComparable<PartidoFecha>
    {
        public int noPartido { get; set; }

        public DateTime FechaPartido { get; set; }

        public string Grupo { get; set; }

        public string Pais1 { get; set; }

        public string Pais2 { get; set; }

        public string Estadio { get; set; }

        public int CompareTo(PartidoFecha obj)
        {
            if (obj == null)
                return 1;

            PartidoFecha otro = obj as PartidoFecha;
            if (otro != null)
                return this.FechaPartido.CompareTo(otro.FechaPartido);
            else
                throw new ArgumentException("Object is not a País");
        }
    }
}

Lab3/Lab3/Controllers/PartidoFechaController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Lab3.DBContext;
using Lab3.Models;
using System.Net;
using AVL;
using System.Web.Script.Serialization;
using Newtonsoft.Json;

namespace Lab3.Controllers
{
    public class PartidoFechaController : Controller
    {
 
        DefaultConnection db = DefaultConnection.getInstance;

        // GET: PartidoFecha
        public ActionResult Index()
        {
            return View(db.fecha.ToList());
        }

        // GET: PartidoFecha/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: PartidoFecha/Create
        public ActionResult Create() 
        {
            //Añadir nodo manualmente
            return View();
        }

        // POST: PartidoFecha/Create
        [HttpPost]
        public ActionResult Create([Bind(Include = "NoPartido, FechaPartido, Grupo, Pais1, Pais2,Estadio")] PartidoFecha nuevo)
        {
            try
            {
                // TODO: Add insert logic here
                
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: PartidoFecha/Edit/5
        public ActionResult Edit(int id) 
        {
            // Carga de archivos
            return View();
        }

        // POST: PartidoFecha/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }



        // GET: PartidoFecha/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: PartidoFecha/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: PartidoFecha/Load
        public ActionResult Load()
        {
            return View();
        }
       
        
        public class ListaNodos
        {
            public List<PartidoFecha> data { get; set; }
        }
        //POST: PartidoFecha/Load
        [HttpPost]
        public ActionResult Load(HttpPostedFileBase jsonFile)
        {
            try
            {
                // TODO: Add insert logic here
                if (Path.GetFileName(jsonFile.FileName).EndsWith(".json"))
                {
                    jsonFile.SaveAs(Server.MapPath("~/JSONFiles" + Path.GetFileName(jsonFile.FileName)));
                    StreamReader sr = new StreamReader(Server.MapPath("~/JSONFiles" + Path.GetFileName(jsonFile.FileName)));
                    string data = sr.ReadToEnd();
                    List<PartidoFecha> partidinhos = new List<PartidoFecha>();
                  //  Lectrura fec = JsonConvert.DeserializeObject<Lectrura>(data);
                     string []g ;
                   char[] separators = { '{', '}'};
                    g = data.Split(separators,System.StringSplitOptions.RemoveEmptyEntries);
                    for (int i = 1; i < g.Length; i++)
                    {
                        
                            string a= "{"+ g[i]+"}";
                            partidinhos.Add(JsonConvert.DeserializeObject<PartidoFecha>(a));
                            i++;
                    }

                    foreach (var item in partidinhos)
                    {
                        Nodo<PartidoFecha> nuevo = new Nodo<PartidoFecha>(item,CompararFecha);
                        int num = db.arbolFecha.Insertar(nuevo);
                        if (num == 1)
                        {
                            db.bitacora.Add("Se ha insertado el nodo");
                            db.fecha.Add(item);
                        }
                        else if (num == 2)
                        {
                            db.bitacora.Add("Se ha insertado y balanceado el arbol");
                            db.fecha.Add(item);
                        }
                        else
                        {
                            db.bitacora.Add("Esto no deberia pasar, aiuda");
                        }
                    }                
                }
                else
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
        }

        private int CompararFecha(PartidoFecha _actual, PartidoFecha _nuevo)
        {
            return _actual.CompareTo(_nuevo);
        }

    }
}

Lab3/Lab3/Views/PartidoFecha/Create.cshtml
@model Lab3.Models.PartidoFecha

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PartidoFecha</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.noPartido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.noPartido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.noPartido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaPartido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaPartido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaPartido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Grupo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Grupo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Grupo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pais1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pais1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pais1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pais2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pais2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pais2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estadio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Estadio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Estadio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Lab3/Lab3/Views/PartidoFecha/Delete.cshtml
@model Lab3.Models.PartidoFecha

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PartidoFecha</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.noPartido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.noPartido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaPartido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaPartido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Grupo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Grupo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pais1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pais1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pais2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pais2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estadio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estadio)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Lab3/Lab3/Views/PartidoFecha/Index.cshtml
@model IEnumerable<Lab3.Models.PartidoFecha>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

    <p>@Html.ActionLink("Crear nuevo partido", "Create")</p>
    <p>@Html.ActionLink("Cargar archivo", "Load")</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.noPartido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaPartido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Grupo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pais1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pais2)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Estadio)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.noPartido)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaPartido)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Grupo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Pais1)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Pais2)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Estadio)
        </td>
        <td>
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>

Lab3/Lab3/Views/PartidoFecha/Load.cshtml
@model Lab3.Models.PartidoFecha

@{
    ViewBag.Title = "Load";
}

<h2>Load</h2>

<body>
    @using (Html.BeginForm("Load", "PartidoFecha", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div>
            JSON file <input type="file" name="jsonFile" />
            <br />
            <input type="submit" value="Import" />
        </div>
    }
</body>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}