Lab3/Lab3/Models/PartidoNo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Lab3.Models
{
    public class PartidoNo: IComparable<PartidoNo>
    {
        public int noPartido { get; set; }
        public DateTime fechaPartido { get; set; }
        public string grupo { get; set; }
        public string pais1 { get; set; }
        public string pais2 { get; set; }
        public string estadio { get; set; }

        public int CompareTo(PartidoNo obj)
        {
            if (obj == null)
                return 1;

            PartidoNo otro = obj as PartidoNo;
            if (otro != null)
                return this.noPartido.CompareTo(otro.noPartido);
            else
                return 0; 
        }
    }
}

Lab3/Lab3/Controllers/PartidoNoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AVL;
using Lab3.DBContext;
using Lab3.Models;
using System.IO;
using System.Net;
using Newtonsoft.Json;

namespace Lab3.Controllers
{
    public class PartidoNoController : Controller
    {

        DefaultConnection db = DefaultConnection.getInstance;

        // GET: PartidoNo
        public ActionResult Index()
        {
            db.arbolNo.Pre(db.arbolNo._raiz);

            return View(db.arbolNo.PreList);
        }

        // GET: PartidoNo/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: PartidoNo/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PartidoNo/Create
        [HttpPost]
        public ActionResult Create([Bind(Include = "NoPartido, FechaPartido, Grupo, Pais1, Pais2,Estadio")] PartidoNo nuevo)
        {
            try
            {
                // TODO: Add insert logic here
                if (nuevo != null)
                {
                    Nodo<PartidoNo> nuevou = new Nodo<PartidoNo>(nuevo, CompararNo);
                    int a = db.arbolNo.Insertar(nuevou);
                    if (a == 1)
                        db.bitacora.Add("Se ha agregado el nodo");
                    else if (a == 2)
                        db.bitacora.Add("Se ha agregado el nodo y se ha balanceado el arbol");
                
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: PartidoNo/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: PartidoNo/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: PartidoNo/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: PartidoNo/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        // GET: PartidoFecha/Load
        public ActionResult Load()
        {
            return View();
        }

        //POST: PartidoFecha/Load
        [HttpPost]
        public ActionResult Load(HttpPostedFileBase jsonFile)
        {
            try
            {
                // TODO: Add insert logic here
                if (Path.GetFileName(jsonFile.FileName).EndsWith(".json"))
                {
                    jsonFile.SaveAs(Server.MapPath("~/JSONFiles" + Path.GetFileName(jsonFile.FileName)));
                    StreamReader sr = new StreamReader(Server.MapPath("~/JSONFiles" + Path.GetFileName(jsonFile.FileName)));
                    string data = sr.ReadToEnd();
                    List<PartidoNo> partidinhos = new List<PartidoNo>();
                    string[] g;
                    char[] separators = { '{', '}' };
                    g = data.Split(separators, StringSplitOptions.RemoveEmptyEntries);
                    for (int i = 1; i < g.Length; i++)
                    {
                        string a = "{" + g[i] + "}";
                        partidinhos.Add(JsonConvert.DeserializeObject<PartidoNo>(a));
                        i++;
                    }

                    foreach (var item in partidinhos)
                    {
                        Nodo<PartidoNo> nuevo = new Nodo<PartidoNo>(item, CompararNo);
                        int num = db.arbolNo.Insertar(nuevo);
                        if (num == 1)
                        {
                            db.bitacora.Add("Se ha insertado el nodo");
                           
                        }
                        else if (num == 2)
                        {
                            db.bitacora.Add("Se ha insertado y balanceado el arbol");
                            
                        }
                    }
                }
                else
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        private int CompararNo(PartidoNo _actual, PartidoNo _nuevo)
        {
            return _actual.CompareTo(_nuevo);
        }
 

    }
}

Lab3/Lab3/Views/PartidoNo/Create.cshtml
@model Lab3.Models.PartidoNo

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PartidoNo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.noPartido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.noPartido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.noPartido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fechaPartido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fechaPartido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fechaPartido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.grupo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.grupo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.grupo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.pais1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.pais1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.pais1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.pais2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.pais2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.pais2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.estadio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.estadio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.estadio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Lab3/Lab3/Views/PartidoNo/Delete.cshtml
@model Lab3.Models.PartidoNo

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PartidoNo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.noPartido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.noPartido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fechaPartido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fechaPartido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.grupo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.grupo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.pais1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.pais1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.pais2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.pais2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.estadio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.estadio)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Lab3/Lab3/Views/PartidoNo/Index.cshtml
@model IEnumerable<Lab3.Models.PartidoNo>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>@Html.ActionLink("Crear nuevo partido", "Create")</p>
<p>@Html.ActionLink("Cargar archivo", "Load")</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.noPartido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fechaPartido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.grupo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.pais1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.pais2)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.estadio)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.noPartido)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.fechaPartido)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.grupo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.pais1)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.pais2)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.estadio)
        </td>
        
    </tr>
}

</table>

Lab3/Lab3/Views/PartidoNo/Load.cshtml
@model Lab3.Models.PartidoNo

@{
    ViewBag.Title = "Load";
}

<h2>Load</h2>

<body>
    @using (Html.BeginForm("Load", "PartidoNo", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div>
            JSON file <input type="file" name="jsonFile" />
            <br />
            <input type="submit" value="Import" />
        </div>
    }
</body>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}